### ISSUE TITLE
Readme Git Wrong

### ISSUE THREAD

**Issue by dredvard** [atomic14/esp32-tft-audio-monitor#1]
Think your readme git is wrong.  I just cloned your repository with recursive.

This is awesome.  Two other modifications (other than the Platformio changes):

in main.cpp:
  //TFT_eSPI *display = new TFT_eSPI(240, 240);
  TFT_eSPI *display = new TFT_eSPI();

In application.cpp:

#define GPIO_BUTTON 0 

And then in Application::loop():

digitalRead(GPIO_BUTTON);

**Comment by cgreening** [comment]
Ooops - bit of schoolboy error in the README! Everything should be fixed now. Thanks for checking out the code.
