### ISSUE TITLE
I2S_BITS_PER_SAMPLE_16BIT creates folding around Fs/2 with ICS-43434 

### ISSUE THREAD

**Issue by jetpax** [atomic14/esp32-tft-audio-monitor#2]
Hi Chris,

Great project !

I noticed that you have folding of the input frequencies around Fs/2.

So for example, your FFT display goes up to 4kHz, but an input signal of 4.1kHz is displayed as 3.9kHz (ie Fs/2-4.1kHz, this alias frequency is apparent even on the time domain plot)

I had similar problems with very different code (MicroPython, though of course still using espidf like Arduino under the hood), with a 1kHz input being aliased to 7kHz (Fs=16000,  I2S_BITS_PER_SAMPLE_16BIT )

![image](https://user-images.githubusercontent.com/6566148/114284637-8471a180-9a51-11eb-83df-ec078175e2e2.png)

At first I thought it was ESP-IDF, but it seems it may be related to how the ICS-43434 decimation filter works; the datasheet shows 32 bitclocks per sample, not 16 (w. 24 bits of data).
In any case, I found that using I2S_BITS_PER_SAMPLE_32BIT and dumping the bottom 8 bits fixed the issue for me.

![image](https://user-images.githubusercontent.com/6566148/114284595-3ceb1580-9a51-11eb-87be-9ef6104008b8.png)

**Comment by cgreening** [comment]
That is some brilliant detective work! I've pushed up a commit to switch to I2S_BITS_PER_SAMPLE_32BIT.

**Comment by stas-sl** [comment]
I know it's an old issue, but I guess finally resolved this mystery, while reading new esp-idf i2s documentation https://docs.espressif.com/projects/esp-idf/en/release-v5.4/esp32/api-reference/peripherals/i2s.html#std-rx-mode

> [!NOTE]
> The receive case is a little bit complicated on ESP32. Firstly, when the data width is 8-bit or 24-bit, the received data will still align with two bytes or four bytes, which means that the valid data are put in the high 8 bits in every two bytes and high 24 bits in every four bytes. For example, the received data will be 0x5A00 when the data on the line is 0x5A in 8-bit width, and 0x0000 5A00 if the data on the line is 0x00 005A. **Secondly, for the 8-bit or 16-bit mono case, the data in buffer is swapped every two data, so it may be necessary to manually swap the data back to the correct order.**

If I manually swap adjacent samples, I see exactly the same folding as mentioned here.

```python
import numpy as np
import matplotlib.pyplot as plt

sr = 16000
duration = 2.0
freq = 1000

t = np.linspace(0, duration, int(sr * duration), endpoint=False)
sine_wave = 0.95 * np.sin(2 * np.pi * freq * t)
sine_wave_swapped = sine_wave.reshape(-1, 2)[:, ::-1].reshape(-1)  # swap adjacent samples

plt.plot(sine_wave[:100], label='original')
plt.plot(sine_wave_swapped[:100], label='swapped')
plt.legend()

plt.magnitude_spectrum(sine_wave, Fs=sr, scale='linear', label='original')
plt.magnitude_spectrum(sine_wave_swapped, Fs=sr, scale='linear', label='swapped')
plt.legend()
```

<img width="1162" height="826" alt="Image" src="https://github.com/user-attachments/assets/5cb30d7b-1392-46be-8f48-e3bcaad73375" />

<img width="1134" height="865" alt="Image" src="https://github.com/user-attachments/assets/00e65def-9b8e-4f16-8804-31a3bf2cbe9c" />

It appears that this issue affected older ESP-IDF versions (4.x) and persists in the newer 5.x versions. However, the 5.x I2S documentation is significantly improved, clearly explaining this detail.
