### ISSUE TITLE
Wiring Diagram for MIC

### ISSUE THREAD

**Issue by anthonyjclarke** [atomic14/esp32-tft-audio-monitor#3]
Not an issue per-se, but do you have any guidance / suggestions on this?

**Comment by cgreening** [comment]
Hi Anthony,

The pins are defined in `src/main.cpp`

```
// i2s pins
i2s_pin_config_t i2s_pins = {
   .bck_io_num = GPIO_NUM_25, 
   .ws_io_num = GPIO_NUM_26,
   .data_out_num = I2S_PIN_NO_CHANGE,
   .data_in_num = GPIO_NUM_27
};
```

Which microphone board are you using - wiring should be pretty straightforward as you just need to connect the pins on the microphone board to the pins on the ESP32.

**Comment by anthonyjclarke** [comment]
Thanks for response. I have a max4466 based board such as this - https://www.ebay.com.au/itm/GY-4466-Microphone-amplifier-module-max4466-adjustable-gain-for-arduino-B-A-/264967449097?_trksid=p2349624.m46890.l49286

I assume this would work? If not I will take your advice on something specific if you wouldn't mind sharing a link. 

Thanks so much

**Comment by cgreening** [comment]
OK, so this is an analogue microphone and you'll need to switch over to using the built-in ADC for input.

In the `config.h` you need to comment out the line:

```
#define USE_I2S_MIC_INPUT
```

That will switch the code over to using the built-in ADC.

The lines here define the GPIO pin that the ADC will be reading from:

```
// Analog Microphone Settings - ADC1_CHANNEL_7 is GPIO35
#define ADC_MIC_CHANNEL ADC1_CHANNEL_7
```

So it will use `GPIO35`.

I've not tested it, but it should work!

As to the wiring, connect:

GND -> GND
VCC -> 3.3V
OUT -> GPIO35

**Comment by cgreening** [comment]
Ah, actually, I'm getting confused with my SDCard example - this code does not have the ADC stuff built in. But it should be possible to do.

**Comment by anthonyjclarke** [comment]
Thanks @cgreening, I was good until your 2nd comment ;-) are you saying I should connect the data out from the GY-4466 to GPIO35 and should work? A little confused but appreciate your help here!

**Comment by cgreening** [comment]
Hey Anthony,

Unfortunately this code doesn't have the ADC I2S code in it. So it will only work with I2S microphones. It should be too much work to change it to use the ADC though, take a look at some of my other examples. I don't have time at the moment to do it, but will circle back.

**Comment by cgreening** [comment]
I'll have some time this weekend to have a look - unfortunately my TTGO display is dead so testing is going to be interesting...

**Comment by anthonyjclarke** [comment]
Happy to gift you one.... shame that it will take 3-4 weeks to arrive ;-)

**Comment by cgreening** [comment]
I've got one coming from Aliexpress - but I can update the code without it.

**Comment by cgreening** [comment]
Have a go with this branch `add-adc-input`

Do:

```
git fetch
git pull
git checkout add-adc-input
```

Completely untested, but if you edit `config.h` and comment out line 16 you should be able to connect your mic to GPIO35.

**Comment by anthonyjclarke** [comment]
Thanks @cgreening, on my list to try this weekend.  Got Git Cloning working, small steps :)

**Comment by anthonyjclarke** [comment]
All working thanks, I purchased some i2S Mic's, so just to try your ADC Code.  Thank you so much!

**Comment by AishwaryaKabadi** [comment]
How can I make code  work with esp32 module with (INMP441 and MAX98357a) and i want it to connect to app (how to get ip of udp ) if any one could help newbie to. make this work
