### ISSUE TITLE
Cloning Git Repo

### ISSUE THREAD

**Issue by anthonyjclarke** [atomic14/esp32-tft-audio-monitor#4]
Sorry for another question,

git clone --recursive git@github.com:atomic14/esp32-tft-audio-monitor.git

Cloning into 'esp32-tft-audio-monitor'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Is there something I need to do to gain permission?

**Comment by cgreening** [comment]
Can you check the instructions here: https://docs.github.com/en/github/authenticating-to-github/troubleshooting-ssh/error-permission-denied-publickey

If you are still having problems (I think you have not added your key to GitHub) you can clone using http:

```
git clone --recursive https://github.com/atomic14/esp32-tft-audio-monitor.git
```
