### ISSUE TITLE
no compile

### ISSUE THREAD

**Issue by girs1982** [atomic14/esp32-tft-audio-monitor#6]
src\Application.cpp:1:22: fatal error: TFT_eSPI.h: No such file or directory

******************************************************************
* Looking for TFT_eSPI.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:TFT_eSPI.h"
* Web  > https://platformio.org/lib/search?query=header:TFT_eSPI.h
*
******************************************************************

compilation terminated.
Compiling .pio\build\ttgo\src\UI\GraphicEqualiser.cpp.o
.pio\libdeps\ttgo\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp: In static member function 'static void ESP32RMTController::interruptHandler(void*)':
.pio\libdeps\ttgo\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:318:10: warning: unused variable 'stuff_to_do' [-Wunused-variable]
     bool stuff_to_do = false;
          ^
*** [.pio\build\ttgo\src\Application.cpp.o] Error 1
src\UI\GraphicEqualiser.cpp:3:22: fatal error: TFT_eSPI.h: No such file or directory

******************************************************************
* Looking for TFT_eSPI.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:TFT_eSPI.h"
* Web  > https://platformio.org/lib/search?query=header:TFT_eSPI.h
*
******************************************************************

compilation terminated.
*** [.pio\build\ttgo\src\UI\GraphicEqualiser.cpp.o] Error 1

**Comment by cgreening** [comment]
Can you clone the repository again and make sure you use `--recursive` flag.

```
git clone --recursive git@github.com:atomic14/esp32-tft-audio-monitor.git
```

**Comment by girs1982** [comment]
Cloning into 'esp32-tft-audio-monitor'...
Warning: Permanently added the RSA host key for IP address '140.82.121.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by cgreening** [comment]
Please check the docs here. I think you have not added your public key to GitHub.

https://docs.github.com/en/github/authenticating-to-github/troubleshooting-ssh/error-permission-denied-publickey
